# Generated by Django 5.0.6 on 2024-05-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_menuitem_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
